<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * AssistanceElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistanceElementRepository extends BaseRepository
{
}
