<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * DTDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTDRepository extends BaseRepository
{
}
