<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * DtdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DtdRepository extends BaseRepository
{
}
