<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * ExportStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExportStatusRepository extends BaseRepository
{
}
