<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * HouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends BaseRepository
{
   
}
