<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * OnlineServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnlineServiceRepository extends BaseRepository
{
}
