<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * ParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamsRepository extends BaseRepository
{
}
