<?php

namespace Crous\Bundle\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{

    /**
     * get regions by criterias
     * 
     * @param array   $criteria
     * @param array   $order
     * @param integer $limit
     * @param integer $offset
     * 
     * @return null|array
     */
    public function getRegions($criteria = array(), $order = array(), $limit = null, $offset = null)
    {
        return $this->findBy($criteria, $order, $limit, $offset);
    }

    /**
     * get total of records by criterias
     * 
     * @param type $criteria
     * @return type
     */
    public function getTotal($criteria = array())
    {
        $qb = $this->createQueryBuilder('o');
        $qb->select('count(o.id)');
        if (!empty($criteria)) {
            foreach ($criteria as $key => $value) {
                $stm = isset($stm) ? 'andWhere' : 'where';
                $qb->{$stm}("o.{$key} = :{$key}");
                $qb->setParameter("{$key}", $value);
            }
        }
        return $qb->getQuery()->getSingleScalarResult();
    }

}
