<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends BaseRepository
{
}
