<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * ScholarshipElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScholarshipElementRepository extends BaseRepository
{
}
