<?php

namespace Crous\Bundle\BackendBundle\Repository;

/**
 * SplashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SplashRepository extends BaseRepository
{
}
