#Crous backend configuration
crous_backend:
    models: 
        user: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\User
            manager_class: \Crous\Bundle\BackendBundle\Manager\UserManager
            form:
                class: ~
                filter_class: ~
        role: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\Role
            manager_class: \Crous\Bundle\BackendBundle\Manager\RoleManager
            form:
                class: ~
                filter_class: ~
        region: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\Region
            manager_class: \Crous\Bundle\BackendBundle\Manager\RegionManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\RegionType
                filter_class: ~
        splash: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\Splash
            manager_class: \Crous\Bundle\BackendBundle\Manager\SplashManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\SplashType
                filter_class: ~
        house: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\House
            manager_class: \Crous\Bundle\BackendBundle\Manager\HouseManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\HouseType
                filter_class: \Crous\Bundle\BackendBundle\Form\Filter\HouseFilter
        service: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\Service
            manager_class: \Crous\Bundle\BackendBundle\Manager\ServiceManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\ServiceType
                filter_class: \Crous\Bundle\BackendBundle\Form\Filter\ServiceFilter
        onlineService: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\OnlineService
            manager_class: \Crous\Bundle\BackendBundle\Manager\OnlineServiceManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\OnlineServiceType
                filter_class: \Crous\Bundle\BackendBundle\Form\Filter\OnlineServiceFilter
        event: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\Event
            manager_class: \Crous\Bundle\BackendBundle\Manager\EventManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\EventType
                filter_class: \Crous\Bundle\BackendBundle\Form\Filter\EventFilter
        dtd: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\Dtd
            manager_class: \Crous\Bundle\BackendBundle\Manager\DtdManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\DtdType
                filter_class: ~
        scholarship: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\Scholarship
            manager_class: \Crous\Bundle\BackendBundle\Manager\ScholarshipManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\ScholarshipType
                filter_class: \Crous\Bundle\BackendBundle\Form\Filter\ScholarshipFilter
        assistance: 
            entity_class: \Crous\Bundle\BackendBundle\Entity\Assistance
            manager_class: \Crous\Bundle\BackendBundle\Manager\AssistanceManager
            form:
                class: \Crous\Bundle\BackendBundle\Form\Type\AssistanceType
                filter_class: \Crous\Bundle\BackendBundle\Form\Filter\AssistanceFilter
        