# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Crous\Bundle\BackendBundle\Entity\User:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        frontend:
            entity: { class: "CrousBackendBundle:User", property: email }
        backend:
            entity: { class: "CrousBackendBundle:User", property: email }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        member_area:
            pattern:    ^/admin/
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
                use_referer: true
                use_forward:    false
                failure_path:   null              
            logout:
                path:   /admin/logout
                target: /admin/login
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            provider: backend
            
        front_area:
            pattern:    ^/(?!(admin)).*$
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /
                use_referer: true
                use_forward:    false
                failure_path:   null              
            logout:
                path:   /logout
                target: /login
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            provider: frontend
    
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_ADMIN_SWITCH]}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
