crous_backend_assistanceelement_add:
    path:     /add/{pid}/{id}
    defaults: { _controller: CrousBackendBundle:AssistanceElement:add, id:null }
    
crous_backend_assistanceelement_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:AssistanceElement:delete}
