crous_backend_dtd_list:
    path:     /
    defaults: { _controller: CrousBackendBundle:Dtd:index }

crous_backend_dtd_add:
    path:     /add/{id}
    defaults: { _controller: CrousBackendBundle:Dtd:add, id:null }
    
crous_backend_dtd_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:Dtd:delete}