crous_backend_event_list:
    path:     /
    defaults: { _controller: CrousBackendBundle:Event:index }

crous_backend_event_add:
    path:     /add/{id}
    defaults: { _controller: CrousBackendBundle:Event:add, id:null }
    
crous_backend_event_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:Event:delete}