crous_backend_house_list:
    path:     /
    defaults: { _controller: CrousBackendBundle:House:index }

crous_backend_house_add:
    path:     /add/{id}
    defaults: { _controller: CrousBackendBundle:House:add, id:null }
    
crous_backend_house_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:House:delete}

crous_backend_house_delete_image:
    path:     /delete-image/{id}
    defaults: { _controller: CrousBackendBundle:House:deleteImage}
    
crous_backend_house_export:
    path:     /export
    defaults: { _controller: CrousBackendBundle:House:export }