crous_backend_house_list:
    path:     /
    defaults: { _controller: CrousBackendBundle:House:index }

crous_backend_house_add:
    path:     /add/{id}
    defaults: { _controller: CrousBackendBundle:House:add, id:null }
    
crous_backend_house_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:House:delete}