crous_backend_onlineservice_list:
    path:     /
    defaults: { _controller: CrousBackendBundle:OnlineService:index }

crous_backend_onlineservice_add:
    path:     /add/{id}
    defaults: { _controller: CrousBackendBundle:OnlineService:add, id:null }
    
crous_backend_onlineservice_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:OnlineService:delete}
    
crous_backend_onlineservice_export:
    path:     /export
    defaults: { _controller: CrousBackendBundle:OnlineService:export }