crous_backend_region_list:
    path:     /
    defaults: { _controller: CrousBackendBundle:Region:index }

crous_backend_region_add:
    path:     /add/{id}
    defaults: { _controller: CrousBackendBundle:Region:add, id:null }
    
crous_backend_region_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:Region:delete}