crous_backend_scholarshipelement_add:
    path:     /add/{pid}/{id}
    defaults: { _controller: CrousBackendBundle:ScholarshipElement:add, id:null }
    
crous_backend_scholarshipelement_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:ScholarshipElement:delete}
