crous_backend_scholarship_list:
    path:     /
    defaults: { _controller: CrousBackendBundle:Scholarship:index }

crous_backend_scholarship_add:
    path:     /add/{id}
    defaults: { _controller: CrousBackendBundle:Scholarship:add, id:null }
    
crous_backend_scholarship_delete:
    path:     /delete/{id}
    defaults: { _controller: CrousBackendBundle:Scholarship:delete}