crous_backend_homepage:
    path:     /
    defaults: { _controller: CrousBackendBundle:Default:index }

crous_backend_login:
    path:     /login
    defaults: { _controller: CrousBackendBundle:Security:login }

crous_backend_login_check:
    path:     /login_check

crous_backend_logout:
    path:     /logout

crous_backend_flux_dashboard:
    path:     /flux-dashboard
    defaults: { _controller: CrousBackendBundle:Default:fluxDashboard }

crous_backend_push_notification:
    path:     /push-notification
    defaults: { _controller: CrousBackendBundle:Push:index }

crous_backend_region:
    resource: "@CrousBackendBundle/Resources/config/routing/region.yml"
    prefix:   /region
    
crous_backend_splash:
    resource: "@CrousBackendBundle/Resources/config/routing/splash.yml"
    prefix:   /splash
    
crous_backend_house:
    resource: "@CrousBackendBundle/Resources/config/routing/house.yml"
    prefix:   /house
    
crous_backend_service:
    resource: "@CrousBackendBundle/Resources/config/routing/service.yml"
    prefix:   /service
    
crous_backend_onlineservice:
    resource: "@CrousBackendBundle/Resources/config/routing/onlineservice.yml"
    prefix:   /onlineservice
    
crous_backend_event:
    resource: "@CrousBackendBundle/Resources/config/routing/event.yml"
    prefix:   /event
    
crous_backend_dtd:
    resource: "@CrousBackendBundle/Resources/config/routing/dtd.yml"
    prefix:   /dtd
    
crous_backend_scholarship:
    resource: "@CrousBackendBundle/Resources/config/routing/scholarship.yml"
    prefix:   /scholarship
    
crous_backend_assistance:
    resource: "@CrousBackendBundle/Resources/config/routing/assistance.yml"
    prefix:   /assistance

crous_backend_scholarshipelement:
    resource: "@CrousBackendBundle/Resources/config/routing/scholarship_element.yml"
    prefix:   /scholarship-element

crous_backend_assistanceelement:
    resource: "@CrousBackendBundle/Resources/config/routing/assistance_element.yml"
    prefix:   /assistance-element
    
crous_backend_user:
    resource: "@CrousBackendBundle/Resources/config/routing/user.yml"
    prefix:   /user

crous_backend_params:
    resource: "@CrousBackendBundle/Resources/config/routing/params.yml"
    prefix:   /params

crous_backend_export:
    resource: "@CrousBackendBundle/Resources/config/routing/export.yml"
    prefix:   /export
