services:
    url_api:
        class: Crous\Bundle\BackendBundle\Service\GoogleUrlApi
        arguments: ["%shorturl_api_key%", "%shorturl_api_url%"]
    entity_factory:
        class: Crous\Bundle\BackendBundle\Service\EntityFactory
        arguments: [@service_container, "%crous_backend.data%"]
    form_factory:
        class: Crous\Bundle\BackendBundle\Service\FormFactory
        arguments: [@service_container, "%crous_backend.data%"]
    manager_factory:
        class: Crous\Bundle\BackendBundle\Service\ManagerFactory
        arguments: [@service_container, "%crous_backend.data%"]
    
